export default {
  configureNotifications,
  registerForPushNotifications,
  getNotificationSettings,
  updateNotificationSettings,
  scheduleLocalNotification,
  cancelScheduledNotification,
  cancelAllScheduledNotifications,
  getAllScheduledNotifications,
  getNotificationPermissions,
  addNotificationResponseReceivedListener,
  addNotificationReceivedListener,
  removeNotificationListener,
  setBadgeCount,
  registerTokenWithServer,
  sendPushNotification,
