# Dependabot configuration file for Vibewell
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Root project dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "13:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    target-branch: "develop"
    labels:
      - "dependencies"
      - "security"
    ignore:
      # Ignore major version updates for these packages
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
    commit-message:
      # Prefix all commit messages with "chore(deps)"
      prefix: "chore(deps)"
      include: "scope"
    reviewers:
      - "vibewell-team"
    
  # Web app dependencies
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "13:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    target-branch: "develop"
    labels:
      - "dependencies"
      - "web"
    groups:
      next-updates:
        patterns:
          - "next*"
          - "@next*"
      react-updates:
        patterns:
          - "react*"
          - "@types/react*"
    commit-message:
      prefix: "chore(deps-web)"
      include: "scope"
    reviewers:
      - "vibewell-team"

  # Mobile app dependencies
  - package-ecosystem: "npm"
    directory: "/apps/mobile"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "13:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    target-branch: "develop"
    labels:
      - "dependencies"
      - "mobile"
    groups:
      expo-updates:
        patterns:
          - "expo*"
      react-native-updates:
        patterns:
          - "react-native*"
          - "@react-native*"
    commit-message:
      prefix: "chore(deps-mobile)"
      include: "scope"
    reviewers:
      - "vibewell-team"

  # Server app dependencies
  - package-ecosystem: "npm"
    directory: "/apps/server"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "13:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    target-branch: "develop"
    labels:
      - "dependencies"
      - "server"
    groups:
      express-updates:
        patterns:
          - "express*"
      prisma-updates:
        patterns:
          - "prisma*"
          - "@prisma*"
    commit-message:
      prefix: "chore(deps-server)"
      include: "scope"
    reviewers:
      - "vibewell-team"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    target-branch: "develop"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    reviewers:
      - "vibewell-team" 