version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_ENABLED=true
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_TLS=false
      - RATE_LIMIT_MODE=redis
    networks:
      - vibewell-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:14
    container_name: vibewell-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vibewell_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - vibewell-network

  # Uncomment if you want to add a pgAdmin interface for database management
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: vibewell-pgadmin
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@vibewell.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped
  #   networks:
  #     - vibewell-network

  redis:
    image: redis:6-alpine
    # Use custom Redis configuration
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password}
    networks:
      - vibewell-network
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-redis_password}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ulimits:
      nofile:
        soft: 26677
        hard: 46677

  # Redis monitoring service
  redis-exporter:
    image: oliver006/redis_exporter:latest
    command: --redis.addr=redis://redis:6379 --redis.password=${REDIS_PASSWORD:-redis_password}
    ports:
      - "9121:9121"
    depends_on:
      - redis
    networks:
      - vibewell-network
    restart: unless-stopped

  # Prometheus for Redis monitoring
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - vibewell-network
    restart: unless-stopped

  # Grafana for Redis monitoring
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3001:3000"
    networks:
      - vibewell-network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=redis-datasource
    restart: unless-stopped

volumes:
  postgres-data:
    name: vibewell-postgres-data
  redis-data:
  prometheus-data:
  grafana-data:

networks:
  vibewell-network:
    name: vibewell-network 