global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'vibewell'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "vibewell_api"
    metrics_path: /metrics
    static_configs:
      - targets: ["web:3000"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093 