// THIS FILE IS AUTO-GENERATED BY scripts/generate-services.js

export type ServiceCategoryKey = 'beauty' | 'wellness';

export interface ServiceCategoryConfig {
  key: ServiceCategoryKey;
  label: string;
  icon: string;
  routeParam: string;
  apiPath: string;
}

export const serviceCategories: ServiceCategoryConfig[] = [
  {
    key: 'beauty',
    label: 'Beauty & Cosmetics',
    icon: 'SparklesIcon',
    routeParam: 'beauty',
    apiPath: '/api/v2/services?category=beauty',
  },
  {
    key: 'wellness',
    label: 'Wellness & Health',
    icon: 'LeafIcon',
    routeParam: 'wellness',
    apiPath: '/api/v2/services?category=wellness',
  },
];