declare module 'cookie-parser';
declare module 'csurf';
declare module 'express-prom-bundle';
declare module 'swagger-ui-express';
declare module 'swagger-jsdoc';
declare module 'speakeasy';
declare module 'fido2-lib';
declare module 'json2csv';
declare module 'base64url';
