import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
{
      type: 'category',
      label: 'User Guide',
      items: [{ type: 'autogenerated', dirName: 'user-guide' }],
{
      type: 'category',
      label: 'Development',
      items: [{ type: 'autogenerated', dirName: 'development' }],
{
      type: 'category',
      label: 'API',
      items: [{ type: 'autogenerated', dirName: 'api' }],
{
      type: 'category',
      label: 'Architecture',
      items: [{ type: 'autogenerated', dirName: 'architecture' }],
{
      type: 'category',
      label: 'Components',
      items: [{ type: 'autogenerated', dirName: 'components' }],
{
      type: 'category',
      label: 'Testing',
      items: [{ type: 'autogenerated', dirName: 'testing' }],
{
      type: 'category',
      label: 'Security',
      items: [{ type: 'autogenerated', dirName: 'security' }],
{
      type: 'category',
      label: 'Deployment',
      items: [{ type: 'autogenerated', dirName: 'deployment' }],
{
      type: 'category',
      label: 'Migration',
      items: [{ type: 'autogenerated', dirName: 'migration' }],
{
      type: 'category',
      label: 'Troubleshooting',
      items: [{ type: 'autogenerated', dirName: 'troubleshooting' }],
],
export default sidebars;
