name: Security Audit

on:
  schedule:
    - cron: '0 2 * * *'   # Daily at 02:00 UTC
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci --legacy-peer-deps
      - run: npx lockfile-lint --path package-lock.json --type npm --allowed-hostname registry.npmjs.org
      - run: npm audit --audit-level=moderate 