name: Setup Repository Secrets

on:
  workflow_dispatch:
    inputs:
      snyk_token:
        description: 'Snyk API Token'
        required: true
      npm_token:
        description: 'NPM Token (if using private registry)'
        required: false

jobs:
  setup-secrets:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      security-events: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Snyk Token
        uses: gliech/create-github-secret-action@v1
        with:
          name: SNYK_TOKEN
          value: ${{ github.event.inputs.snyk_token }}
          pa_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure NPM Token
        if: ${{ github.event.inputs.npm_token != '' }}
        uses: gliech/create-github-secret-action@v1
        with:
          name: NPM_TOKEN
          value: ${{ github.event.inputs.npm_token }}
          pa_token: ${{ secrets.GITHUB_TOKEN }} 