name: Web CI
on:
  push:
    paths:
      - 'apps/web/**'
  pull_request:
    paths:
      - 'apps/web/**'
jobs:
  clean-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci --workspace vibewell-web
      - name: Run clean:tests script
        run: npm run clean:tests:web
  test:
    runs-on: ubuntu-latest
    needs: clean-tests
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci --workspace vibewell-web
      - name: Build web app
        run: npm run build --workspace vibewell-web
      - name: Run tests with coverage
        run: npm run test:ci --workspace vibewell-web 